# Generated by Django 3.0.6 on 2020-05-09 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blackbox', '0002_auto_20200508_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
